sudo: false
dist: stretch
language: go
services:
- docker
go:
- "1.11"
stages:
- test
- build
- deploy
before_install:
- make dep
jobs:
  include:
  - stage: test
    name: Go
    script: 
    - make fmt
    - make vet 
    - make gocyclo
    - make golint 
    - make ineffassign
    - make misspell
    - make test
  - name: Vue
    script: make docker_npm_test
  - stage: build
    name: "Go"
    script: make linux darwin rpi windows
  - name: "Vue"
    script: make docker_npm_build
  - stage: deploy
    script: make linux darwin rpi windows
    name: "GitHub releases"
    deploy:
      provider: releases
      api_key: ${GITHUB_API_KEY}
      file: 
      - out/logga-linux-amd64
      - out/logga-darwin-amd64
      - out/logga-linux-arm
      - out/logga-windows-amd64.exe
      skip_cleanup: true
      draft: true
      on:
        tags: true
  - name: "Docker Hub"
    provider: script
    script:
    - "echo $DOCKER_PASSWORD | docker login -u amimof --password-stdin"
    - make docker_compile
    on:
      branch: master