sudo: false
dist: stretch
language: go
go:
- "1.11"
stages:
- test
- build
- deploy
before_install:
- make dep
jobs:
  include:
  - stage: test
    script: 
    - make fmt
    - make vet 
    - make gocyclo
    - make golint 
    - make ineffassign
    - make misspell
    - make test
  - stage: build
    script:
    - make linux
  - stage: deploy
    deploy:
      provider: releases
      api_key: ${GITHUB_API_KEY}
      file: out/logga-linux-amd64
      skip_cleanup: true
      script: skip
      on:
        tags: true